<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>TeaScript</string>
    <key>scopeName</key>
    <string>source.tea</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#expr</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>expr</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#arrow</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#parens</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comprehension</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#named-arg</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#words</string>
          </dict>
        </array>
      </dict>
      <key>arg-list</key>
      <dict>
        <key>name</key>
        <string>keyword</string>
        <key>begin</key>
        <string>\s*args\s+(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>text.html</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\})</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>text.html</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#arg-name</string>
          </dict>
        </array>
      </dict>
      <key>arg-name</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
            <key>begin</key>
            <string>([a-zA-Z][a-zA-Z0-9_\$]*\s+)?\{</string>
            <key>end</key>
            <string>\}</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#arg-name</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
            <key>match</key>
            <string>[a-zA-Z][a-zA-Z0-9_\$]*</string>
          </dict>
        </array>
      </dict>
      <key>argument</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
            <key>match</key>
            <string>@[a-zA-Z\$][a-zA-Z0-9_\$]*</string>
          </dict>
        </array>
      </dict>
      <key>array</key>
      <dict>
        <key>name</key>
        <string>text.array</string>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>\]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expr</string>
          </dict>
        </array>
      </dict>
      <key>arrow</key>
      <dict>
        <key>name</key>
        <string>keyword</string>
        <key>match</key>
        <string>=&gt;</string>
      </dict>
      <key>code-block</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>text.code-block</string>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>(?=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expr</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line</string>
            <key>begin</key>
            <string>###</string>
            <key>end</key>
            <string>###</string>
            <key>contentName</key>
            <string>comment.line</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line</string>
            <key>begin</key>
            <string>#</string>
            <key>end</key>
            <string>(?=$)</string>
            <key>contentName</key>
            <string>comment.line</string>
          </dict>
        </array>
      </dict>
      <key>comprehension</key>
      <dict>
        <key>match</key>
        <string>(from)\s+([a-zA-Z][a-zA-Z0-9_\$]*)\s+:</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
          </dict>
        </dict>
      </dict>
      <key>constants</key>
      <dict>
        <key>name</key>
        <string>constant.language</string>
        <key>match</key>
        <string>\b(true|false|null|void)\b</string>
      </dict>
      <key>function</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>contentName</key>
            <string>text.html</string>
            <key>begin</key>
            <string>(async\s+)?fn\*?\s+([a-zA-Z\$][a-zA-Z0-9_\$]*\s+)?(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.html</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.html</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#argument</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expr</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>contentName</key>
            <string>text.html</string>
            <key>match</key>
            <string>(async\s+)?fn\*?((\{)([a-zA-Z\$][a-zA-Z0-9_\$]*)(,\s*[a-zA-Z\$][a-zA-Z0-9_\$]*)*(\}))?</string>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.language</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>text.html</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>text.html</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>contentName</key>
            <string>text.html</string>
            <key>begin</key>
            <string>(async\s+)?fn\*?\s+([a-zA-Z][a-zA-Z0-9_\$]*)\s+(?==&gt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expr</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>match</key>
            <string>=&gt;|debugger</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>begin</key>
            <string>(for(\s+(ever|await)?)|\@catch|if|safeguard(\^)?|guard)</string>
            <key>end</key>
            <string>(\})</string>
            <key>contentName</key>
            <string>text.html</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.html</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code-block</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#expr</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>begin</key>
            <string>(\@finally|try)</string>
            <key>end</key>
            <string>(\})</string>
            <key>contentName</key>
            <string>text.html</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.html</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code-block</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>begin</key>
            <string>export\s+(\{)</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.html</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>text.html</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>text.export-block</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#keyword-export-entry</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>match</key>
            <string>^export (default )?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>match</key>
            <string>\b(yield|await|let|mut)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword</string>
            <key>match</key>
            <string>^\s*import\s+([^\s]+)\s(from)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter constant.language</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>keyword-export-entry</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>text.export-block</string>
            <key>match</key>
            <string>([a-zA-Z\$][a-zA-Z0-9_\$]*)\s+(as)\s+([a-zA-Z\$][a-zA-Z0-9_\$]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.parameter</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
            <key>match</key>
            <string>[a-zA-Z\$][a-zA-Z0-9_\$]*</string>
          </dict>
        </array>
      </dict>
      <key>named-arg</key>
      <dict>
        <key>name</key>
        <string>variable.parameter</string>
        <key>match</key>
        <string>:[a-zA-Z][a-zA-Z0-9_\$]*</string>
      </dict>
      <key>number</key>
      <dict>
        <key>name</key>
        <string>constant.numeric</string>
        <key>match</key>
        <string>\d+(\.\d+)?((e|E)(\+|\-)?\d+)?</string>
      </dict>
      <key>object</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>\}</string>
        <key>name</key>
        <string>text.html</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#object-key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expr</string>
          </dict>
        </array>
      </dict>
      <key>object-key</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
            <key>begin</key>
            <string>:\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expr</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.parameter</string>
            <key>begin</key>
            <string>:</string>
            <key>end</key>
            <string>\s</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expr</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
            <key>match</key>
            <string>(\.\.\.|&lt;&lt;&lt;|&gt;&gt;&gt;|&lt;&lt;|&gt;&gt;|&lt;\+|\+&gt;|&amp;|\*|%|=|&lt;|&gt;|\-|\+|\/|\||\!|\~)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
            <key>begin</key>
            <string>(await|typeof|delete)\{</string>
            <key>end</key>
            <string>\}</string>
            <key>contentName</key>
            <string>text.html</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expr</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
            <key>begin</key>
            <string>instance&lt;</string>
            <key>end</key>
            <string>&gt;</string>
            <key>contentName</key>
            <string>text.html</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expr</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>parens</key>
      <dict>
        <key>name</key>
        <string>text.html</string>
        <key>begin</key>
        <string>(?&lt;=\s)\(</string>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expr</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.template</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#string-interpolation</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#string-escapes</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>string-escapes</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape</string>
        <key>match</key>
        <string>\\(x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|u\{[0-9A-Fa-f]+\}|[0-2][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|#)</string>
      </dict>
      <key>string-interpolation</key>
      <dict>
        <key>begin</key>
        <string>#\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>constant.character.escape</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>contentName</key>
        <string>meta.embedded.line</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expr</string>
          </dict>
        </array>
      </dict>
      <key>template</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.template.js</string>
            <key>begin</key>
            <string>([_$[:alpha:]][_$[:alnum:]]*)?(`)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.tagged-template.js</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.template.begin.js</string>
              </dict>
            </dict>
            <key>end</key>
            <string>`</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.template.end.js</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array/>
          </dict>
        </array>
      </dict>
      <key>words</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.tag</string>
            <key>match</key>
            <string>[a-zA-Z\$][a-zA-Z0-9_\$]*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
            <key>match</key>
            <string>\??(\.)[a-zA-Z\$][a-zA-Z0-9_\$]*\??(?=\()</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.normal</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>support.variable.property</string>
            <key>match</key>
            <string>\??(\.)[a-zA-Z\$][a-zA-Z0-9_\$]*</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>text.normal</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
